name: Auto-merge Dependencies

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ${{ vars.RUNNER_SMALL }}
    if: >
      github.event.pull_request.user.login == 'dependabot[bot]' ||
      github.event.pull_request.user.login == 'articulate-automation[bot]'
    steps:
      - uses: actions/create-github-app-token@v3
        id: token
        with:
          client-id: ${{ vars.AUTOMATION_CLIENT_ID }}
          private-key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
      - name: Approve PR
        env:
          # Approve as Botzo to work around CODEOWNERS requirement
          GH_TOKEN: ${{ secrets.BOTZO_GH_TOKEN }}
          PR: ${{ github.event.pull_request.number }}
        run: gh pr review --approve "$PR" -R "$GITHUB_REPOSITORY"
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
          PR: ${{ github.event.pull_request.number }}
        run: gh pr merge --auto --squash "$PR" -R "$GITHUB_REPOSITORY"
