name: CI

on:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image:
          - 12-lambda
          - 12-stretch-slim
          - 12-buster-slim
          - 14-lambda
          - 14-stretch-slim
          - 14-buster-slim
          - 16-lambda
          - 16-stretch-slim
          - 16-buster-slim
          - 16-bullseye-slim
          - 18-bullseye-slim
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.image }}/Dockerfile
          push: false
          tags: articulate/articulate-node:${{ matrix.image }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=gha,scope=${{ github.workflow }}-${{ matrix.image }}
          cache-to: type=gha,scope=${{ github.workflow }}-${{ matrix.image }},mode=max
