name: Lint

on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Find Dockerfiles
        id: scan
        run: echo "dockerfiles=$(find . -name Dockerfile | cut -c3- | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
    outputs:
      dockerfiles: ${{ steps.scan.outputs.dockerfiles }}
  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    strategy:
      fail-fast: false
      matrix:
        dockerfile: ${{ fromJSON(needs.setup.outputs.dockerfiles) }}
    steps:
      - uses: actions/checkout@v5
      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # pin@v3.3.0
        with:
          dockerfile: ${{ matrix.dockerfile }}
          ignore: DL3008,DL3016,DL3033,DL3041
