name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - 14-lambda
          - 14-buster-slim
          - 16-lambda
          - 16-buster-slim
          - 16-bullseye-slim
          - 18-bullseye-slim
          - 18-lambda
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # pin@v3.1.0
        with:
          dockerfile: ${{ matrix.image }}/Dockerfile
          ignore: DL3008,DL3016,DL3033
