name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - 12-lambda
          - 12-stretch-slim
          - 12-buster-slim
          - 14-lambda
          - 14-stretch-slim
          - 14-buster-slim
          - 16-lambda
          - 16-stretch-slim
          - 16-buster-slim
          - 16-bullseye-slim
          - 18-bullseye-slim
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@0a6d062e780d218ea909a18365e0ab2e36d09612 # pin@v2.0.0
        with:
          dockerfile: ${{ matrix.image }}/Dockerfile
          ignore: DL3008,DL3016,DL3033
